DB_URL=jdbc:mysql://localhost:3306/internhub
DB_USERNAME=root
DB_PASSWORD=202005

JWT_SECRET=VEhJU19JU19BX1ZFUlRfTE9OR19TRUNSRVRfS0VZX0ZPUl9JTlRFUk5IVUI=

CLOUDINARY_CLOUD_NAME=dm6mkgjic
CLOUDINARY_API_KEY=571736255616594
CLOUDINARY_API_SECRET=n40tJouoZMb7LZMZ6w6sB72yv6w

GEMINI_API_KEY=AQ.Ab8RN6JAkqw67Y_Yb_mK5LyG0HVOEfwlFt2wKrjSef49F5Ug3Q

MAIL_USERNAME=hocn3707@gmail.com
MAIL_PASSWORD=aiur eier itxk mrna
